#+title:  CSS Grid Notes

CSS Grid es utilizado para ordenar y/o alinear el diseño de una página web.

* ¿Qué es display?

Es una propiedad de CSS que establece los tipos de visualización interna y externa de un elemento. La tipo externa establece la participacion de un elemento en flow layout; la tipo interna establece el layout(Diseño) de los hijos.

*  Display de tipo grid

Definimos display como grid en los contenedores. Esto habilita todas las propiedades de grid explícitas e implícitas.

** Ejemplo
#+begin_src css
.container-element {
    display: grid;
}
#+end_src

* Propiedad grid-gap
 Esta propiedad de grid genera espacio entre los elementos para ello podemos usar siguientes  unidades de miedida: px, %,em,vh,vw, etc.

** Unidades de longitud relativa
 em:           Tamaño de letra del elemento padre, en el caso de propiedades tipográficas como font-size, y
                    tamaño de la fuente del propio elemento en el caso de otras propiedades, como width.
ex: 	        Altura x de la fuente del elemento.
ch: 	        La medida de avance (ancho) del glifo "0" de la letra del elemento.
rem:           Tamaño de la letra del elemento raíz.
lh:    	        Altura de la línea del elemento.
vw:   	        1% del ancho de la ventana gráfica.
vh:         	1% de la altura de la ventana gráfica.
vmin: 	1% de la dimensión más pequeña de la ventana gráfica.
vmax: 	1% de la dimensión más grande de la ventana gráfica.

** Unidades de longitud absoluta

cm 	Centímetros 	                1cm = 96px/2,54
mm 	Milímetros 	                        1mm = 1/10 de 1cm
Q 	Cuartos de milímetros 	1Q = 1/40 de 1cm
in 	Pulgadas 	                        1in = 2,54cm = 96px
pc 	Picas 	                                1pc = 1/6 de 1in
pt 	Puntos 	                                1pt = 1/72 de 1in
px 	Píxeles 	                                1px = 1/96 de 1in

** Ejemplo
 #+begin_src css
 .container-element {
     display: grid;
     grid-gap: 10px;
 }
#+end_src

* Propiedad justify-content
 Esta propiedad define cómo el navegador distribuye el espacio entre y alrededor de los elementos
 a lo largo del eje principal de su contenedor.

~Nota:~ Los ejemplos del 1 al 5 son alineados en el eje horizontal, esto puede causar
 dudas debido a que los elementos estan ordenados de forma vertical por defecto.

** Ejemplo 1 propieda center

 #+begin_src css
 .container-element {
     display: grid;
     grid-gap: 10px;
     justify-content: center;
 }
#+end_src

** Ejemplo 2 propiedad start
Alinea los elementos al lado izquierdo (left).

 #+begin_src css
 .container-element {
     display: grid;
     grid-gap: 10px;
     justify-content: start;
 }
#+end_src

** Ejemplo 3 propiedad end
Alinea los elementos al lado derecho (right).

 #+begin_src css
 .container-element {
     display: grid;
     grid-gap: 10px;
     justify-content: end;
 }
#+end_src

** Ejemplo 4 propiedad space-between
Es curioso en lugar de tener todo el espacio del contenedor, toma solo
el espacio nestricamente necesario, como carne al vacío.

 #+begin_src css
 .container-element {
     display: grid;
     height: 100vh;
     width: 100vw;
     justify-content: space-between;
 }
#+end_src

** Ejemplo 5 propiedad space-around
Parce que centra los elementos en el eje horizontal.

 #+begin_src css
  .container-element {
      display: grid;
      height: 100vh;
      width: 100vw;
      justify-content: space-around;
  }
#+end_src

** Ejemplo 6 propiedad space-evenly
Distribuir elementos uniformemente, los elementos tienen el mismo espacio alrededor de ellos.

 #+begin_src css
  .container-element {
      display: grid;
      height: 100vh;
      width: 100vw;
      justify-content: space-evenly;
  }
#+end_src

** Ejemplo 7 propiedad stretch
Distribuir elementos uniformemente, estira los elementos de tamaño 'automático' para
que quepan en el contenedor.
 #+begin_src css
  .container-element {
      display: grid;
      height: 100vh;
      width: 100vw;
      justify-content: stretch;
  }
#+end_src


~Nota:~ Globales, alinea todos los elementos

** Ejemplo 1  propiedad initial
Parece que deja los elementos en su estado por defecto, lo probé en =flex= y =grid=
con =flex= por defectotodo queda en horizontal con espacios en tre los elementos, mientras que en =grid=
queda en vertical y ambos al lado izquierdo (left).
#+begin_src css
  .container-element {
      display: grid;
      height: 100vh;
      width: 100vw;
      justify-content: initial;
  }
#+end_src

** Ejemplo 2 propiedad inherit
~Inherit: Eredar~
 Al definir un atributo como inherit estamos diciendo que ese algo hereda el valor de el atributo del contenedor padre.

 #+begin_src css
  .container-element {
      display: grid;
      height: 100vh;
      width: 100vw;
      justify-content: inherit;
  }
#+end_src

** Ejemplo 3  propiedad unset
~unset: desarmar~



#+begin_src css
  .container-element {
      display: grid;
      height: 100vh;
      width: 100vw;
      justify-content: unset;
  }
#+end_src
~Nota: Vertical~
